// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: parquet_options/parquet_options.proto

package parquet_options

import (
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ParquetMessageOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// As long as table_name is not blank,
	// a schema is generated for top-level messages in each file.
	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
}

func (x *ParquetMessageOptions) Reset() {
	*x = ParquetMessageOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parquet_options_parquet_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParquetMessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParquetMessageOptions) ProtoMessage() {}

func (x *ParquetMessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_parquet_options_parquet_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParquetMessageOptions.ProtoReflect.Descriptor instead.
func (*ParquetMessageOptions) Descriptor() ([]byte, []int) {
	return file_parquet_options_parquet_options_proto_rawDescGZIP(), []int{0}
}

func (x *ParquetMessageOptions) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type ParquetFieldOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimestampUnit string `protobuf:"bytes,1,opt,name=timestamp_unit,json=timestampUnit,proto3" json:"timestamp_unit,omitempty"`
}

func (x *ParquetFieldOptions) Reset() {
	*x = ParquetFieldOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parquet_options_parquet_options_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParquetFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParquetFieldOptions) ProtoMessage() {}

func (x *ParquetFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_parquet_options_parquet_options_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParquetFieldOptions.ProtoReflect.Descriptor instead.
func (*ParquetFieldOptions) Descriptor() ([]byte, []int) {
	return file_parquet_options_parquet_options_proto_rawDescGZIP(), []int{1}
}

func (x *ParquetFieldOptions) GetTimestampUnit() string {
	if x != nil {
		return x.TimestampUnit
	}
	return ""
}

var file_parquet_options_parquet_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.MessageOptions)(nil),
		ExtensionType: (*ParquetMessageOptions)(nil),
		Field:         1022,
		Name:          "extensions.parquet_options.v1.parquet_message_opts",
		Tag:           "bytes,1022,opt,name=parquet_message_opts",
		Filename:      "parquet_options/parquet_options.proto",
	},
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*ParquetFieldOptions)(nil),
		Field:         1022,
		Name:          "extensions.parquet_options.v1.parquet_field_opts",
		Tag:           "bytes,1022,opt,name=parquet_field_opts",
		Filename:      "parquet_options/parquet_options.proto",
	},
}

// Extension fields to descriptor.MessageOptions.
var (
	// optional extensions.parquet_options.v1.ParquetMessageOptions parquet_message_opts = 1022;
	E_ParquetMessageOpts = &file_parquet_options_parquet_options_proto_extTypes[0]
)

// Extension fields to descriptor.FieldOptions.
var (
	// optional extensions.parquet_options.v1.ParquetFieldOptions parquet_field_opts = 1022;
	E_ParquetFieldOpts = &file_parquet_options_parquet_options_proto_extTypes[1]
)

var File_parquet_options_parquet_options_proto protoreflect.FileDescriptor

var file_parquet_options_parquet_options_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x61, 0x72, 0x71, 0x75, 0x65, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2f, 0x70, 0x61, 0x72, 0x71, 0x75, 0x65, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x61, 0x72, 0x71, 0x75, 0x65, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x15, 0x50, 0x61, 0x72, 0x71,
	0x75, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x3c, 0x0a, 0x13, 0x50, 0x61, 0x72, 0x71, 0x75, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x55, 0x6e, 0x69, 0x74, 0x3a, 0x88,
	0x01, 0x0a, 0x14, 0x70, 0x61, 0x72, 0x71, 0x75, 0x65, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x6f, 0x70, 0x74, 0x73, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xfe, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x34, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x61, 0x72,
	0x71, 0x75, 0x65, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x61, 0x72, 0x71, 0x75, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x12, 0x70, 0x61, 0x72, 0x71, 0x75, 0x65, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x73, 0x3a, 0x80, 0x01, 0x0a, 0x12, 0x70, 0x61,
	0x72, 0x71, 0x75, 0x65, 0x74, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6f, 0x70, 0x74, 0x73,
	0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0xfe, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x61, 0x72, 0x71, 0x75, 0x65, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x71, 0x75, 0x65, 0x74, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x10, 0x70, 0x61, 0x72, 0x71,
	0x75, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x73, 0x42, 0x13, 0x5a, 0x11,
	0x2e, 0x2f, 0x70, 0x61, 0x72, 0x71, 0x75, 0x65, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_parquet_options_parquet_options_proto_rawDescOnce sync.Once
	file_parquet_options_parquet_options_proto_rawDescData = file_parquet_options_parquet_options_proto_rawDesc
)

func file_parquet_options_parquet_options_proto_rawDescGZIP() []byte {
	file_parquet_options_parquet_options_proto_rawDescOnce.Do(func() {
		file_parquet_options_parquet_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_parquet_options_parquet_options_proto_rawDescData)
	})
	return file_parquet_options_parquet_options_proto_rawDescData
}

var file_parquet_options_parquet_options_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_parquet_options_parquet_options_proto_goTypes = []interface{}{
	(*ParquetMessageOptions)(nil),     // 0: extensions.parquet_options.v1.ParquetMessageOptions
	(*ParquetFieldOptions)(nil),       // 1: extensions.parquet_options.v1.ParquetFieldOptions
	(*descriptor.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
	(*descriptor.FieldOptions)(nil),   // 3: google.protobuf.FieldOptions
}
var file_parquet_options_parquet_options_proto_depIdxs = []int32{
	2, // 0: extensions.parquet_options.v1.parquet_message_opts:extendee -> google.protobuf.MessageOptions
	3, // 1: extensions.parquet_options.v1.parquet_field_opts:extendee -> google.protobuf.FieldOptions
	0, // 2: extensions.parquet_options.v1.parquet_message_opts:type_name -> extensions.parquet_options.v1.ParquetMessageOptions
	1, // 3: extensions.parquet_options.v1.parquet_field_opts:type_name -> extensions.parquet_options.v1.ParquetFieldOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_parquet_options_parquet_options_proto_init() }
func file_parquet_options_parquet_options_proto_init() {
	if File_parquet_options_parquet_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_parquet_options_parquet_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParquetMessageOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_parquet_options_parquet_options_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParquetFieldOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_parquet_options_parquet_options_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_parquet_options_parquet_options_proto_goTypes,
		DependencyIndexes: file_parquet_options_parquet_options_proto_depIdxs,
		MessageInfos:      file_parquet_options_parquet_options_proto_msgTypes,
		ExtensionInfos:    file_parquet_options_parquet_options_proto_extTypes,
	}.Build()
	File_parquet_options_parquet_options_proto = out.File
	file_parquet_options_parquet_options_proto_rawDesc = nil
	file_parquet_options_parquet_options_proto_goTypes = nil
	file_parquet_options_parquet_options_proto_depIdxs = nil
}
